version: '3'
services:
  document-center-fe:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
        NEXT_PUBLIC_APP_URL: https://document-center.cerana.tech
    
