name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-e2e-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    # Install npm dependencies, cache them correctly
    # and run all Cypress tests
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies for frontend
      run: |
        npm ci
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        build: npm run build
        start: npm run start
        browser: chrome
        wait-on: 'http://localhost:3000'
        

  
  build-and-push:
    needs: [cypress-e2e-test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/document-center-fe:v${{ github.run_number }}
      # - name: Update k8s config
      #   run: |
      #     sed -i "s|yjack0000cs12/document-center-fe:v[0-9]*|yjack0000cs12/document-center-fe:v${{ github.run_number }}|" ./k8s/deploys.yml
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git config --global user.name "github-actions[bot]"
      #     git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git          
      #     git add ./k8s/deploys.yml
      #     git commit -m "Update deployment image to v${{ github.run_number }}"
      #     git push